spring:
  datasource:
    url: ${JDBC_URL}
    username: ${USER_NAME}
    password: ${PASS_WORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    open-in-view: false